services:
  - type: web
    name: fm-global-rag-agent
    runtime: node
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO # Update this
    branch: main
    rootDir: use-cases/agent-factory-with-subagents/agents/rag_agent_asrs
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false # Set in Render dashboard
      - key: SUPABASE_ANON_KEY  
        sync: false # Set in Render dashboard
      - key: OPENAI_API_KEY
        sync: false # Set in Render dashboard